### ISSUE TITLE
Torch not able to use GPU with latest NVIDIA-driver

### ISSUE THREAD

**Issue by OriginalJohann** [virchau13/automatic1111-webui-nix#13]
Hello everyone who might read this. I know, that nothing is really changing here but I still hope we can find a solution somehow.

Thank's to all the advice in previous issues I was able to run webUI until recently. I really don't know when it stopped working (I am sure it worked at the start of 24.05) but now it doesn't

At first I tried using the "default" repo after re-pulling everything, but instantly got prompted with the _RuntimeError: Torch is not able to use GPU_ blabla. So I first switched to nix-23.11 and got hit with a nvidia driver missmatch (545 vs. 450) so I am now using nix-24.05 (this is obvious but I tried everything step by step). 

```Traceback (most recent call last):
  File "/data/ai/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/data/ai/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/data/ai/stable-diffusion-webui/modules/launch_utils.py", line 388, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
```

After still getting the error, and noticing, that **nvidia-smi** inside of the dev-shell was showing an **ERR!** next to **CUDA**, I installed the cudatoolkit globally and removed it from impl.nix. With that, my nvidia-smi output was fixed.

This is my usage of nvidia:

```# Make sure opengl is enabled
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  nixpkgs.config = {
    # Allow unfree packages
    allowUnfree = true;

    # Accept NVIDIA license
    nvidia.acceptLicense = true;
  };

  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (builtins.parseDrvName pkg.name).name [
      "nvidia-x11"
      "steam"
      "steam-original"
      "steam-run"
    ];

  hardware.nvidia = {
    # Modsetting is needed for most wayland compositors
    modesetting.enable = true;
    # Use the open source version of the kernel module
    open = true;
    # Enable the nvidia settings menu
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
```

As I said, it worked in the past and I also have no problems with e.g. gaming.

In my homemanager profile I am also setting the **CUDA_VISIBLE_DEVICES** according to my nvidia-smi outside of the shell:

```# Make GPU 0 visible for usage with CUDA (see nvidia-smi)
    CUDA_VISIBLE_DEVICES = "0";```

**Comment by ogkloo** [comment]
This presumably happens because the version of `cudatoolkit` in the flake differs from the one installed on your system. You can see this happen in `nvidia-smi`, since it'll show the version in both. Try running it from within the flake and then from without. Your solution here is pulling in the system version.

Another way to solve this is to ensure both the flake and your system are on the same version of nixpkgs, which is to say that the nix-channel marked nixos in the output of `sudo nix-channel --list` matches `inputs.nixpkgs.url` in `flake.nix`:

```
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-XX.YY
```

```nix
# flake.nix
{
    description = "AUTOMATIC1111/stable-diffusion-webui flake";

    inputs = {
        # This field must match the output of nix-channel
        nixpkgs.url = github:NixOS/nixpkgs/nixos-XX.YY;
        flake-utils.url = github:numtide/flake-utils;
    };

    outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachSystem flake-utils.lib.defaultSystems (system: let
            pkgs = import nixpkgs {
                inherit system;
                config.allowUnfree = true;
            };
        in {
            devShells.default = throw "You need to specify which output you want: CPU, ROCm, or CUDA.";
            devShells.cpu = import ./impl.nix { inherit pkgs; variant = "CPU"; };
            devShells.cuda = import ./impl.nix { inherit pkgs; variant = "CUDA"; };
            devShells.rocm = import ./impl.nix { inherit pkgs; variant = "ROCM"; };
        }
    );
}
```

I'm not sure what can be done to make this process easier in the future. The system and flake version of cudatoolkit need to match but obviously that kind of defeats the whole purpose of flakes.
